---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: Import Vpc Variables
     include_vars: vars/bastion_setup
   - name: Import Vpc setup Variables
     include_vars: vars/output_vars